
TEST_HEADER = b"\x01"

KEEP_ALIVE = b"\x10"

LOGIN_REQUEST_HEADER = b"\x20"
STATUS_REQUEST_HEADER = b"\x21"
TRANSFER_REQUEST_HEADER = b"\x22"



LOGIN_SUCCESS_HEADER = b"\30"
STATUS_SUCCESS_HEADER = b"\31"
TRANSFER_SUCCESS_HEADER = b"\32"
GENERIC_ERROR_HEADER = b"\40"
LOGIN_ERROR_HEADER = b"\41"
TRANSFER_ERROR_NOTARGET_HEADER = b"\42"
TRANSFER_ERROR_NOMONEY_HEADER = b"\43"